-- Insert sample products for MYSAir
-- Air Diffusion Products
INSERT INTO products (name, description, category, subcategory, price, image_url, technical_specs, is_featured) VALUES
('Rejilla Lineal Premium RL-300', 'Rejilla lineal de alta calidad con lamas orientables para distribución uniforme del aire', 'air_diffusion', 'grilles', 89.99, '/linear-grille-premium.jpg', '{"material": "Aluminio anodizado", "sizes": ["300x100", "400x100", "500x100"], "airflow": "200-800 m³/h", "pressure": "50-200 Pa"}', true),
('Difusor Circular DC-200', 'Difusor circular con núcleo fijo y anillos direccionales ajustables', 'air_diffusion', 'diffusers', 125.50, '/circular-diffuser.jpg', '{"material": "Acero galvanizado", "diameter": "200mm", "airflow": "150-600 m³/h", "throw": "2-4m"}', true),
('Compuerta Reguladora CR-250', 'Compuerta de regulación manual con indicador de posición', 'air_diffusion', 'dampers', 67.75, '/manual-damper.jpg', '{"material": "Galvanizado", "sizes": ["200x200", "250x250", "300x300"], "leakage": "Clase 2", "pressure": "500 Pa"}', false),
('Rejilla de Retorno RR-400', 'Rejilla de retorno con filtro desmontable y marco oculto', 'air_diffusion', 'grilles', 95.00, '/return-grille.jpg', '{"material": "Aluminio", "sizes": ["400x200", "500x250", "600x300"], "filter": "G4 incluido", "mounting": "Marco oculto"}', false),
('Difusor Cuadrado DQ-300', 'Difusor cuadrado de 4 vías con deflectores ajustables', 'air_diffusion', 'diffusers', 145.25, '/square-diffuser.jpg', '{"material": "Aluminio", "size": "300x300mm", "airflow": "200-800 m³/h", "pattern": "4 vías", "throw": "1.5-3m"}', true),

-- Smart Systems Products  
('Sistema de Zonificación ZoneMaster Pro', 'Sistema completo de zonificación inteligente con 8 zonas independientes', 'smart_systems', 'zoning', 1299.99, '/zoning-system.jpg', '{"zones": 8, "connectivity": "WiFi + Zigbee", "sensors": "Temperatura y humedad", "compatibility": "Alexa, Google, Apple HomeKit", "power": "24V AC"}', true),
('Termostato Inteligente SmartClima T1', 'Termostato táctil con conectividad WiFi y programación avanzada', 'smart_systems', 'controls', 189.99, '/smart-thermostat.jpg', '{"display": "5 pulgadas táctil", "connectivity": "WiFi 2.4GHz", "sensors": "Temperatura, humedad, presencia", "battery": "Recargable Li-ion", "compatibility": "iOS/Android"}', true),
('Sensor de Ambiente MultiSense', 'Sensor inalámbrico de temperatura, humedad y calidad del aire', 'smart_systems', 'controls', 79.99, '/environment-sensor.jpg', '{"sensors": ["Temperatura", "Humedad", "CO2", "VOC"], "connectivity": "Zigbee 3.0", "battery": "2 años autonomía", "range": "100m exterior"}', false),
('Actuador de Compuerta SmartDamper', 'Actuador motorizado para automatización de compuertas existentes', 'smart_systems', 'zoning', 159.99, '/smart-actuator.jpg', '{"torque": "10 Nm", "power": "24V AC/DC", "control": "0-10V / PWM", "feedback": "Posición analógica", "mounting": "Universal"}', false),
('Central de Control ClimateHub', 'Unidad central para gestión integral del sistema de climatización', 'smart_systems', 'controls', 899.99, '/climate-hub.jpg', '{"zones": "Hasta 16", "protocols": ["Modbus", "BACnet", "KNX"], "display": "7 pulgadas", "storage": "Datos locales", "backup": "UPS integrado"}', true);
